parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  requireConfigFile: false
env:
  es2017: true
  browser: true

extends: 'htmlacademy/vanilla'
<<<<<<< HEAD
parser: '@babel/eslint-parser'
=======
parser: '@babel/eslint-parser'
>>>>>>> f0c3c43dbb4f7afda6f6f0732254f6fc12e2b634
